### PR TITLE
Remove useless f-strings

### PR DESCRIPTION
**Pull request by liZe**

### CODE REVIEW

**Comment by wjt** [comment]
Why does this PR target the `lize/machine-location` branch rather than `master`?

**Comment by wjt** [comment]
I imagined that we would fix this and https://github.com/endlessm/azafea/pull/138 before landing the changes to the handling of location IDs.

**Review by wjt — APPROVED** [review]
The change here looks fine, it's only the target branch I am concerned about!

**Comment by liZe** [comment]
> The change here looks fine, it's only the target branch I am concerned about!

You’re right. I’ve changed this PR and #138 to be merged on master, I’ll push only the needed commits on this branch and ping you.

**Comment by liZe** [comment]
@wjt I’ve updated the two PRs to be merged on `master`.

**Pull request merged**
