### PR TITLE
T28742 Parental controls migration

### PR DESCRIPTION
**Pull request by pwithnall**
This adds the missing database migration script for the new parental controls events, which I neglected to add in the initial commit.

I haven’t tested this, since setting up postgresql and redis containers in order to do so is a fairly involved effort. We’ll see if it works when doing the test database migrationm

https://phabricator.endlessm.com/T28742

### CODE REVIEW

**Comment by pwithnall** [comment]
Looks like I have to please the CI first

**Comment by wjt** [comment]
@adarnimrod 
since you spotted this which I overlooked in the last PR, perhaps you could review?

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by pwithnall** [comment]
(the Ubuntu repository mirrors used by the CI are returning 404s)

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by wjt** [comment]
Travis may not respond to the same commands as our Jenkins

**Comment by dbnicholson** [comment]
> (the Ubuntu repository mirrors used by the CI are returning 404s)

This was actually brought up the other day in #103. Our actual build uses alpine in https://github.com/endlessm/eos-administration/blob/master/docker/azafea/Dockerfile. We should try to get those synced up even if the one here doesn't totally represent our real deployment.

**Comment by wjt** [comment]
The indices look to be just the standard ones on the foreign keys. We may want more indices on these tables in the future but I don't think we should block on that.

**Comment by pwithnall** [comment]
Yeah, I don’t have any great ideas for things which need additional indexing.

I just updated it to add a missing `import` spotted by `pylint`.

**Comment by dbnicholson** [comment]
I don't know how to retrigger the Travis CI but now that #106 is merged it should get past the docker build now.

**Comment by pwithnall** [comment]
> I don't know how to retrigger the Travis CI but now that #106 is merged it should get past the docker build now.

Open the Travis results and press the restart build button in the top-right (you have to be logged in to Travis). I’ve done so, and it seems to be making progress, thanks!

**Comment by pwithnall** [comment]
Updated to satisfy lint.

**Comment by dbnicholson** [comment]
Given that @adarnimrod approved and the CI is passing now, I'm going to merge this. We can make sure it's working properly in the dev environment first.

**Pull request merged**
