### PR TITLE
Store the "allowed empty payload" information in the table class

### PR DESCRIPTION
**Pull request by liZe**
To be merged after #115.

### CODE REVIEW

**Comment by liZe** [comment]
I don’t know why tests are not launched on Travis.

**Comment by wjt** [comment]
Try reopening the PR targeting master?

**Comment by wjt** [comment]
Ah, deleting the base branch did the job. Now, how to retrigger CI…

**Comment by mwleeds** [comment]
bot, retest this please

**Review by wjt — APPROVED** [review]

**Pull request merged**
